In [1]:
import numpy as np

In [2]:
lis=[1,2,3]

In [3]:
type(lis)

list

In [4]:
np.array(lis)

array([1, 2, 3])

In [6]:
matrix=[[1,2,3],[5,4,8]]
matrix

[[1, 2, 3], [5, 4, 8]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [5, 4, 8]])

In [8]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [11]:
np.zeros((5,2),int)
         

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5,3)#always fall between 0 and 1

array([[0.36204459, 0.30074387, 0.73939095],
       [0.34376582, 0.52273496, 0.04254025],
       [0.96879457, 0.36476187, 0.9717482 ],
       [0.81329301, 0.21243936, 0.49320594],
       [0.25051141, 0.02662804, 0.49261895]])

In [20]:
np.random.randn(12,4)

array([[ 1.08037441, -0.85268962, -0.16387439,  0.276874  ],
       [-1.9155176 ,  0.09363529, -0.98769608,  0.13562521],
       [ 2.24751246, -1.00368832,  0.01779483,  0.45464045],
       [-1.40429432, -1.87971286, -0.72407574, -0.21445481],
       [ 1.90793233,  2.95545964,  0.06360046,  0.89894994],
       [-0.80223378, -0.27906322,  0.9398422 , -0.55513225],
       [ 0.38179663, -0.22846223,  0.92030387, -1.22795001],
       [ 0.46545127, -0.09248347,  0.07039759,  1.07424982],
       [ 1.08677761, -0.69823466,  0.29834988,  0.23225344],
       [ 1.38029759, -0.87906906,  0.2294971 , -0.20999567],
       [-2.86497665, -1.1541621 ,  0.23562307,  0.56000705],
       [-0.03546184,  0.70798916, -1.34441894,  1.04273791]])

In [23]:
np.random.randint(0,5,(2,5))

array([[0, 4, 2, 2, 2],
       [1, 4, 2, 1, 3]])

In [27]:
np.random.seed(3)#do computations in the same cell
np.random.randint(1,5,(5,3))

array([[3, 1, 2],
       [4, 1, 1],
       [1, 2, 2],
       [4, 3, 4],
       [2, 2, 3]])

In [29]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr=np.random.randint(0,10,10)
ranarr

array([5, 7, 6, 0, 4, 7, 8, 1, 6, 2])

In [32]:
ranarr.max()

8

In [33]:
ranarr.min()

0

In [34]:
ranarr.argmin()#gives the indices of the minimum value

3

In [35]:
ranarr.argmax()#give the maximm of the maximum value

6

In [36]:
ranarr.shape

(10,)

In [37]:
ranarr.reshape(2,5)

array([[5, 7, 6, 0, 4],
       [7, 8, 1, 6, 2]])

In [38]:
ar=np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
ar[8]

8

In [41]:
print(ar[2:])
print(ar[:5])

[ 2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]


In [42]:
ar[:3]=100
ar


array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [43]:
ar=np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a=ar[0:5]
a

array([0, 1, 2, 3, 4])

In [45]:
a[:]=99
a

array([99, 99, 99, 99, 99])

In [46]:
ar#original array also effected

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arcopy=ar.copy()

In [48]:
arcopy[:]=67
arcopy

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [49]:
ar#by copying you wont effect the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
ar2=np.random.randint(1,10,(3,3))
ar2

array([[3, 2, 4],
       [6, 9, 2],
       [9, 8, 9]])

In [52]:
ar2.shape

(3, 3)

In [51]:
ar2[1,]

array([6, 9, 2])

In [53]:
ar2[1,1]

9

In [54]:
ar2[1][1]

9

In [60]:
ar2[0:2,0:3]

array([[3, 2, 4],
       [6, 9, 2]])

In [61]:
#conditional selection
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [63]:
boll_arr=a>4
boll_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
a[boll_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#operations

In [68]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
arr+arr#arrays must be the same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
arr/arr

C:\Users\Mukes\AppData\Local\Temp/ipykernel_13692/1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
1/arr

C:\Users\Mukes\AppData\Local\Temp/ipykernel_13692/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [74]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [76]:
np.log(arr)

C:\Users\Mukes\AppData\Local\Temp/ipykernel_13692/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [77]:
arr.sum()

45

In [78]:
arr.mean()

4.5

In [79]:
arr.var()

8.25

In [80]:
arr.std()

2.8722813232690143

In [82]:
a=np.random.randint(0,10,(2,5))
a

array([[1, 0, 5, 4, 1],
       [5, 4, 7, 6, 0]])

In [83]:
a.sum()

33

In [84]:
a.sum(axis=0)#adds towards the columns if it is 1 then it would be across tthe rows

array([ 6,  4, 12, 10,  1])